### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by sequency** [est77/ramen#11]
When trying to build (step "make") (on openSUSE 13.1) I get the following error:

[ 16%] Building CXX object ramen/CMakeFiles/ramen.dir/anim/any_curve.cpp.o
In file included from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:14:0,
                 from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/shape_key.hpp:19,
                 from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/shape_curve.hpp:13,
                 from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/any_curve.cpp:8:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml.hpp: In function ‘bool ramen::get_optional_value(const YAML::Node&, const string&, T&)’:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml.hpp:39:33: error: ‘const class YAML::Node’ has no member named ‘FindValue’
  if( const YAML::Node _n = node.FindValue( key))
                                 ^
In file included from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/shape_key.hpp:19:0,
                 from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/shape_curve.hpp:13,
                 from /home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/anim/any_curve.cpp:8:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp: At global scope:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:33:10: error: ‘Iterator’ in namespace ‘YAML’ does not name a type
  typedef YAML::Iterator const_iterator; 
          ^
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:34:2: error: ‘const_iterator’ does not name a type
  const_iterator begin() const { return node_->begin();}
  ^
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:35:2: error: ‘const_iterator’ does not name a type
  const_iterator end() const  { return node_->end();}
  ^
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp: In member function ‘ramen::serialization::yaml_node_t ramen::serialization::yaml_node_t::operator[](int) const’:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:43:47: error: taking address of temporary [-fpermissive]
   return yaml_node_t( parent_, &(_node_)[index], version());
                                               ^
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp: In member function ‘bool ramen::serialization::yaml_node_t::get_optional_value(const string&, T&) const’:
/home/ankalagon/Downloads/Ramen/r1/ramen2/ramen-master/ramen/serialization/yaml_node.hpp:64:42: error: ‘const class YAML::Node’ has no member named ‘FindValue’
         if( const YAML::Node _n = node_->FindValue( key))
                                          ^
make[2]: *_\* [ramen/CMakeFiles/ramen.dir/anim/any_curve.cpp.o] Fehler 1
make[1]: **\* [ramen/CMakeFiles/ramen.dir/all] Fehler 2
make: **\* [all] Fehler 2

**Comment by est77** [comment]
I think that you need an older version of yaml-cpp. A release from around the same time when ramen was being developed.

**Comment by devernay** [comment]
Or you could try (and maybe contribute to) https://github.com/MrKepzie/Natron !
